### ISSUE TITLE
require bumped into php 7.1

### ISSUE THREAD

**Issue by geminorum** [endroid/simple-excel#1]
why suddenly bumping to `>=7.1` ? 

`PHPOffice/PhpSpreadsheet` is still on `^5.6|^7.0`

**Comment by endroid** [comment]
Hi @geminorum this is mainly because I work in more modern versions myself and it takes quite some time to keep supporting older versions throughout my libraries or work with many different versions. I agree that the requirement might not be strictly necessary for this library but it enables me to maintain my code.
